# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  inputs:
    command: 'install'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'

# - task: Npm@1
#   inputs:
#     command: 'publish'
#     publishEndpoint: 'npm.org'
- task: Npm@1
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: '218da33c-9e6e-4d3f-bd06-17943f115076/5ae8c143-7c99-400a-88ba-19842033edfd'